version: '3.8'
services:
  vprodb: #conatiner name
    build:
      context: ./Docker-files/db
    image: kais18/projectdb
    container_name: vprodb
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass
  
  vprocache01:
    image: memcached
    ports:
      - "11211:11211"
 
  vpromq01:
    image: rabbitmq
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  vproapp: #conatiner name
    build:
      context: ./Docker-files/app
    image: kais18/projectapp
    container_name: vproapp
    ports:
      - "8080:8080"
    volumes:
      - vproappdata:/usr/local/tomcar/webapps

  vproweb: #conatiner name
    build:
      context: ./Docker-files/web
    image: kais18/projectweb
    container_name: vproweb
    ports:
      - "80:80"
    volumes:
      - vprodbdata:/usr/local/tomcar/webapps

volumes:
  vprodbdata: {}
  vproappdata: {}